import type { Metadata } from "next";
import "./globals.css";
import WlExtensionLoader from "@/components/WlExtensionLoader";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={`${roboto.variable} font-roboto antialiased`}>
        <WlExtensionLoader />
        {children}
      </body>
    </html>
  );
}
